// Hand-authored "confusables" — the near-identical services the SAA-C03 exam loves to
// contrast. These are the highest-ROI differentiations for avoiding trap answers.
import type { Comparison } from '../types';

export const comparisons: Comparison[] = [
  {
    id: 'cmp-sg-nacl',
    domainId: 'd1',
    title: 'Security Group vs Network ACL',
    items: ['Security Group', 'Network ACL'],
    rows: [
      { label: 'Applies at', values: ['Instance / ENI level', 'Subnet level'] },
      { label: 'State', values: ['Stateful — return traffic auto-allowed', 'Stateless — must allow return traffic explicitly'] },
      { label: 'Rules', values: ['Allow rules only', 'Allow AND Deny rules'] },
      { label: 'Evaluation', values: ['All rules evaluated together', 'Lowest rule number first; first match wins'] },
      { label: 'Default', values: ['Denies inbound, allows outbound', 'Default NACL allows all; custom NACL denies all'] },
    ],
    bottomLine: 'Use Security Groups as the primary control (stateful, per-instance). Use NACLs for coarse subnet-wide DENY rules, e.g. blocking a specific IP range.',
    tags: ['VPC', 'Security Groups', 'NACL'],
  },
  {
    id: 'cmp-sqs-sns',
    domainId: 'd2',
    title: 'SQS vs SNS',
    items: ['Amazon SQS', 'Amazon SNS'],
    rows: [
      { label: 'Model', values: ['Message queue (pull)', 'Pub/sub (push)'] },
      { label: 'Delivery', values: ['One consumer group processes each message', 'Fan-out: every subscriber gets a copy'] },
      { label: 'Retention', values: ['Stored up to 14 days until processed', 'Not stored; pushed to current subscribers'] },
      { label: 'Best for', values: ['Decouple + buffer work, absorb spikes', 'Broadcast one event to many endpoints'] },
    ],
    bottomLine: 'Buffer/decouple work between tiers → SQS. Notify many targets from one event → SNS. Durable fan-out → SNS topic to multiple SQS queues.',
    tags: ['SQS', 'SNS'],
  },
  {
    id: 'cmp-multiaz-readreplica',
    domainId: 'd2',
    title: 'RDS Multi-AZ vs Read Replica',
    items: ['Multi-AZ', 'Read Replica'],
    rows: [
      { label: 'Purpose', values: ['High availability / failover', 'Scale read traffic'] },
      { label: 'Replication', values: ['Synchronous to standby', 'Asynchronous'] },
      { label: 'Secondary readable?', values: ['No — standby is passive', 'Yes — serves reads'] },
      { label: 'Failover', values: ['Automatic to standby', 'Manual promotion to standalone DB'] },
      { label: 'Region', values: ['Same region', 'Can be cross-region'] },
    ],
    bottomLine: 'Availability/durability → Multi-AZ. Read scaling → Read Replicas. Different problems — combine them for HA + read scale.',
    tags: ['RDS', 'Aurora'],
  },
  {
    id: 'cmp-gp3-io2',
    domainId: 'd3',
    title: 'EBS gp3 vs io2',
    items: ['gp3 (General Purpose SSD)', 'io1 / io2 (Provisioned IOPS SSD)'],
    rows: [
      { label: 'Best for', values: ['Most workloads; cost-effective baseline', 'I/O-intensive, latency-sensitive databases'] },
      { label: 'IOPS', values: ['3,000 baseline, configurable up to 80,000', 'Provisioned up to 256,000 (every io2 is now Block Express)'] },
      { label: 'Max size', values: ['64 TiB', '64 TiB (io1: 16 TiB)'] },
      { label: 'Cost', values: ['Lower; IOPS/throughput decoupled from size', 'Higher; pay per provisioned IOPS'] },
      { label: 'Durability', values: ['~99.8–99.9%', 'io2 up to 99.999%'] },
    ],
    bottomLine: 'Default to gp3 for price/performance. Choose io2 only for sustained very high IOPS or the highest durability requirement.',
    tags: ['EBS'],
  },
  {
    id: 'cmp-cognito-pools',
    domainId: 'd1',
    title: 'Cognito User Pool vs Identity Pool',
    items: ['User Pool', 'Identity Pool (Federated Identities)'],
    rows: [
      { label: 'Answers', values: ['"Who are you?" — authentication', '"What can you access?" — authorization'] },
      { label: 'Gives you', values: ['Sign-up/sign-in, user directory, JWT tokens', 'Temporary AWS credentials via STS'] },
      { label: 'Use to', values: ['Manage app users, social/enterprise login', 'Let users call AWS services (S3, DynamoDB)'] },
    ],
    bottomLine: 'User Pool = authentication + user directory. Identity Pool = exchange an identity for temporary AWS credentials. Often used together.',
    tags: ['Cognito', 'STS'],
  },
  {
    id: 'cmp-cloudfront-ga',
    domainId: 'd3',
    title: 'CloudFront vs Global Accelerator',
    items: ['CloudFront', 'Global Accelerator'],
    rows: [
      { label: 'Optimizes', values: ['Content delivery via caching at edge', 'Network path to your endpoints (no caching)'] },
      { label: 'Best for', values: ['Cacheable web content, media, APIs', 'TCP/UDP apps, gaming, non-HTTP, static anycast IPs'] },
      { label: 'Entry point', values: ['Edge cache serves/caches content', 'Two static anycast IPs, traffic enters AWS backbone early'] },
    ],
    bottomLine: 'Cacheable HTTP content → CloudFront. Non-HTTP / need static IPs / fastest path to a regional endpoint → Global Accelerator.',
    tags: ['CloudFront', 'Global Accelerator'],
  },
  {
    id: 'cmp-alb-nlb',
    domainId: 'd3',
    title: 'ALB vs NLB',
    items: ['Application Load Balancer', 'Network Load Balancer'],
    rows: [
      { label: 'Layer', values: ['Layer 7 (HTTP/HTTPS)', 'Layer 4 (TCP/UDP/TLS)'] },
      { label: 'Routing', values: ['Path/host/header-based rules', 'Flow-based; forwards by connection'] },
      { label: 'Performance', values: ['Rich features, higher latency', 'Ultra-low latency, millions of req/s'] },
      { label: 'Static IP', values: ['No (use DNS name)', 'Yes — one static IP per AZ'] },
    ],
    bottomLine: 'HTTP routing, redirects, host/path rules → ALB. Extreme performance, static IPs, or non-HTTP protocols → NLB.',
    tags: ['ELB', 'ALB', 'NLB'],
  },
  {
    id: 'cmp-endpoints',
    domainId: 'd1',
    title: 'Gateway Endpoint vs Interface Endpoint',
    items: ['Gateway Endpoint', 'Interface Endpoint (PrivateLink)'],
    rows: [
      { label: 'Supports', values: ['S3 and DynamoDB only', 'Most AWS services + your own services'] },
      { label: 'How it works', values: ['Route table entry to the service', 'Elastic network interface with a private IP'] },
      { label: 'Cost', values: ['Free', 'Hourly + per-GB charge'] },
    ],
    bottomLine: 'Private access to S3/DynamoDB → free Gateway Endpoint. Private access to any other service → Interface Endpoint (PrivateLink).',
    tags: ['VPC', 'PrivateLink', 'S3', 'DynamoDB'],
  },
  {
    id: 'cmp-purchasing',
    domainId: 'd4',
    title: 'On-Demand vs Reserved / Savings Plans vs Spot',
    items: ['Reserved Instances / Savings Plans', 'Spot Instances', 'On-Demand'],
    rows: [
      { label: 'Discount', values: ['Up to ~72% for 1–3 yr commitment', 'Up to ~90% off On-Demand', 'None (baseline price)'] },
      { label: 'Commitment', values: ['1 or 3 years', 'None, but can be reclaimed with 2-min notice', 'None'] },
      { label: 'Best for', values: ['Steady, predictable baseline load', 'Fault-tolerant, flexible, interruptible batch', 'Short-term / unpredictable spikes'] },
    ],
    bottomLine: 'Predictable baseline → Savings Plans/RIs. Interruptible & stateless → Spot. Spiky/unknown → On-Demand. Real designs blend all three.',
    tags: ['EC2', 'Savings Plans', 'Spot'],
  },
  {
    id: 'cmp-s3-classes',
    domainId: 'd4',
    title: 'S3 Storage Classes',
    items: ['S3 Standard', 'Standard-IA', 'One Zone-IA', 'Glacier Instant Retrieval', 'Glacier Deep Archive'],
    rows: [
      { label: 'Access pattern', values: ['Frequent', 'Infrequent', 'Infrequent', 'Archive, instant access', 'Cold archive'] },
      { label: 'AZs', values: ['≥3', '≥3', '1 (lower availability — durability is still 11 nines)', '≥3', '≥3'] },
      { label: 'Retrieval', values: ['Immediate', 'Immediate', 'Immediate', 'Milliseconds', 'Standard ~12h, Bulk up to 48h'] },
      { label: 'Cost profile', values: ['Highest storage', 'Lower storage + retrieval fee', 'Cheapest IA (single AZ)', 'Cheap archive, ms access', 'Cheapest storage'] },
    ],
    bottomLine: 'Unknown/changing access → Intelligent-Tiering. Recreatable infrequent data → One Zone-IA. Archives needing instant reads → Glacier Instant; deepest/cheapest → Deep Archive.',
    tags: ['S3', 'Glacier'],
  },
  {
    id: 'cmp-ecs-eks-fargate',
    domainId: 'd3',
    title: 'ECS vs EKS vs Fargate',
    items: ['Amazon ECS', 'Amazon EKS', 'AWS Fargate'],
    rows: [
      { label: 'What it is', values: ['AWS-native container orchestrator', 'Managed Kubernetes control plane', 'Serverless compute for containers'] },
      { label: 'You manage', values: ['Tasks/services (simpler)', 'Kubernetes (portable, complex)', 'Nothing — no servers to scale'] },
      { label: 'Runs on', values: ['EC2 or Fargate', 'EC2 or Fargate', 'It IS the compute layer'] },
      { label: 'Pick when', values: ['Simple AWS-integrated orchestration', 'You need Kubernetes / portability', 'You want zero infrastructure ops'] },
    ],
    bottomLine: 'ECS = simple AWS orchestration; EKS = Kubernetes when you truly need it; Fargate = the serverless launch type that removes EC2 management (works under both ECS and EKS).',
    tags: ['ECS', 'EKS', 'Fargate'],
  },
  {
    id: 'cmp-dx-vpn',
    domainId: 'd3',
    title: 'Direct Connect vs Site-to-Site VPN',
    items: ['AWS Direct Connect', 'Site-to-Site VPN'],
    rows: [
      { label: 'Connection', values: ['Private, dedicated physical link', 'Encrypted tunnel over the public internet'] },
      { label: 'Performance', values: ['Consistent, low latency, high bandwidth', 'Variable (internet-dependent)'] },
      { label: 'Setup & cost', values: ['Weeks to provision, higher cost', 'Minutes, low cost'] },
      { label: 'Best for', values: ['Steady high-throughput hybrid, predictable latency', 'Quick/cheap connectivity or a backup link'] },
    ],
    bottomLine: 'Need consistent performance and bandwidth → Direct Connect. Need it fast/cheap, or as a backup → Site-to-Site VPN (often VPN backs up Direct Connect).',
    tags: ['Direct Connect', 'VPN', 'Hybrid'],
  },
  {
    id: 'cmp-observability',
    domainId: 'd2',
    title: 'CloudWatch vs CloudTrail vs X-Ray',
    items: ['Amazon CloudWatch', 'AWS CloudTrail', 'AWS X-Ray'],
    rows: [
      { label: 'Answers', values: ['How is it performing?', 'Who did what?', 'Where is the latency?'] },
      { label: 'Data', values: ['Metrics, logs, alarms, dashboards', 'API call history (account activity)', 'Distributed request traces'] },
      { label: 'Use for', values: ['Monitoring & alerting (and triggering Auto Scaling)', 'Security audit & compliance', 'Debugging microservice latency'] },
    ],
    bottomLine: 'Performance & alarms → CloudWatch. Audit of API calls → CloudTrail. Trace a request across services → X-Ray.',
    tags: ['CloudWatch', 'CloudTrail', 'X-Ray'],
  },
  {
    id: 'cmp-peering-tgw',
    domainId: 'd4',
    title: 'VPC Peering vs Transit Gateway',
    items: ['VPC Peering', 'Transit Gateway'],
    rows: [
      { label: 'Topology', values: ['One-to-one (non-transitive)', 'Hub-and-spoke (transitive)'] },
      { label: 'Scale', values: ['Becomes a complex mesh as VPCs grow', 'Central hub for many VPCs and on-prem'] },
      { label: 'Transitive routing', values: ['No', 'Yes'] },
      { label: 'Cost', values: ['No hourly charge (pay data transfer only)', 'Hourly attachment + data processing charge'] },
    ],
    bottomLine: 'A few VPCs and lowest cost → VPC peering. Many VPCs, on-prem, or transitive routing → Transit Gateway.',
    tags: ['VPC', 'Transit Gateway'],
  },
  {
    id: 'cmp-scp-iam-boundary',
    domainId: 'd1',
    title: 'SCP vs IAM policy vs Permission boundary',
    items: ['Service Control Policy', 'IAM identity policy', 'Permission boundary'],
    rows: [
      { label: 'Applies to', values: ['A whole account/OU (via Organizations)', 'A user or role', 'A user or role (as a cap)'] },
      { label: 'Effect', values: ['Sets the MAX for the account; never grants', 'Grants permissions', 'Caps the max an identity can be granted; never grants'] },
      { label: 'Managed by', values: ['Central/org security team', 'Account admins', 'A delegating admin'] },
    ],
    bottomLine: 'Effective permissions = SCP ∩ identity policy ∩ permission boundary, minus any explicit Deny. Only identity/resource policies GRANT; SCPs and boundaries only LIMIT.',
    tags: ['Organizations', 'IAM', 'SCP'],
  },
];
