// AUTO-GENERATED alias map: Topic.services free-text names (used across the older
// generated content) to canonical Service ids in aws-saa-c03.services.ts. Lets
// TopicDetailScreen's service pills link to a real service definition even where the
// display string is a variant, e.g. "AWS IAM (roles)" -> "iam". Assigned to
// ContentPack.serviceAliases in aws-saa-c03.ts.
export const serviceAliases: Record<string, string> = {
  "AWS App Runner": "app-runner",
  "AWS Application Migration Service (MGN)": "mgn",
  "AWS Audit Manager": "audit-manager",
  "AWS Auto Scaling": "aws-auto-scaling",
  "AWS Backup": "aws-backup",
  "AWS Batch": "batch",
  "AWS Budgets": "budgets",
  "AWS Certificate Manager (ACM)": "acm",
  "AWS Client VPN": "client-vpn",
  "AWS CloudTrail": "cloudtrail",
  "AWS Compute Optimizer": "compute-optimizer",
  "AWS Config": "config",
  "AWS Config Rules": "config",
  "AWS Control Tower": "control-tower",
  "AWS Cost Explorer": "cost-explorer",
  "AWS Cost and Usage Report (CUR)": "cur",
  "AWS DataSync": "datasync",
  "AWS Database Migration Service (DMS)": "dms",
  "AWS Direct Connect": "direct-connect",
  "AWS Direct Connect Gateway": "direct-connect",
  "AWS Directory Service (AWS Managed Microsoft AD, AD Connector, Simple AD)": "directory-service",
  "AWS Elastic Disaster Recovery": "drs",
  "AWS Fargate": "fargate",
  "AWS Global Accelerator": "global-accelerator",
  "AWS Glue": "glue",
  "AWS Health": "aws-health",
  "AWS IAM (roles)": "iam",
  "AWS IAM Identity Center": "iam-identity-center",
  "AWS Identity and Access Management (IAM)": "iam",
  "AWS KMS": "kms",
  "AWS Lake Formation": "lake-formation",
  "AWS Lambda": "lambda",
  "AWS Network Firewall": "network-firewall",
  "AWS Organizations": "organizations",
  "AWS Organizations (Consolidated Billing)": "organizations",
  "AWS PrivateLink": "privatelink",
  "AWS Savings Plans": "savings-plans",
  "AWS Schema Conversion Tool (SCT)": "sct",
  "AWS Secrets Manager": "secrets-manager",
  "AWS Security Hub": "security-hub",
  "AWS Security Token Service (STS)": "sts",
  "AWS Service Catalog": "service-catalog",
  "AWS Service Quotas": "service-quotas",
  "AWS Shield": "shield",
  "AWS Site-to-Site VPN": "site-to-site-vpn",
  "AWS Snow Family": "snow-family",
  "AWS Snow Family (Snowball Edge)": "snow-family",
  "AWS Snowball": "snow-family",
  "AWS Step Functions": "step-functions",
  "AWS Storage Gateway": "storage-gateway",
  "AWS Systems Manager": "systems-manager",
  "AWS Systems Manager Automation": "systems-manager",
  "AWS Systems Manager Parameter Store": "systems-manager-parameter-store",
  "AWS Systems Manager Session Manager": "systems-manager",
  "AWS Transfer Family": "transfer-family",
  "AWS Transit Gateway": "transit-gateway",
  "AWS Trusted Advisor": "trusted-advisor",
  "AWS WAF": "waf",
  "AWS X-Ray": "x-ray",
  "Amazon API Gateway": "api-gateway",
  "Amazon Athena": "athena",
  "Amazon Aurora": "aurora",
  "Amazon Aurora Global Database": "aurora",
  "Amazon CloudFront": "cloudfront",
  "Amazon CloudWatch": "cloudwatch",
  "Amazon CloudWatch Logs": "cloudwatch",
  "Amazon CloudWatch Logs Insights": "cloudwatch",
  "Amazon Cognito (user pools and identity pools)": "cognito",
  "Amazon DynamoDB": "dynamodb",
  "Amazon EBS": "ebs",
  "Amazon EC2": "ec2",
  "Amazon EC2 Auto Scaling": "ec2-auto-scaling",
  "Amazon EC2 Instance Store": "ec2-instance-store",
  "Amazon ECR": "ecr",
  "Amazon ECS": "ecs",
  "Amazon EFS": "efs",
  "Amazon EKS": "eks",
  "Amazon EMR": "emr",
  "Amazon ElastiCache": "elasticache",
  "Amazon EventBridge": "eventbridge",
  "Amazon FSx for Lustre": "fsx-lustre",
  "Amazon FSx for Windows File Server": "fsx-windows",
  "Amazon Kinesis Data Firehose (Amazon Data Firehose)": "kinesis-firehose",
  "Amazon Kinesis Data Streams": "kinesis-data-streams",
  "Amazon MSK": "msk",
  "Amazon Managed Service for Apache Flink (Kinesis Data Analytics)": "managed-flink",
  "Amazon QuickSight": "quicksight",
  "Amazon RDS": "rds",
  "Amazon RDS (Multi-AZ)": "rds",
  "Amazon RDS Multi-AZ": "rds",
  "Amazon RDS Proxy": "rds-proxy",
  "Amazon RDS Read Replicas": "rds",
  "Amazon Redshift": "redshift",
  "Amazon Route 53": "route53",
  "Amazon Route 53 Resolver": "route53",
  "Amazon S3": "s3",
  "Amazon S3 Block Public Access": "s3",
  "Amazon S3 Glacier": "s3",
  "Amazon SNS": "sns",
  "Amazon SQS": "sqs",
  "Amazon VPC": "vpc",
  "Application Load Balancer": "elb",
  "Application Load Balancer (ALB)": "elb",
  "Aurora Serverless v2": "aurora",
  "CloudWatch Agent": "cloudwatch",
  "CloudWatch Alarms": "cloudwatch",
  "Cost Allocation Tags": "cost-allocation-tags",
  "DynamoDB Accelerator (DAX)": "dax",
  "DynamoDB global tables": "dynamodb",
  "DynamoDB point-in-time recovery (PITR)": "dynamodb",
  "EBS Snapshots": "ebs",
  "EC2 Placement Groups": "ec2-placement-groups",
  "EC2 Reserved Instances": "ec2-purchasing-options",
  "EC2 Spot Instances": "ec2-purchasing-options",
  "Elastic Fabric Adapter (EFA)": "ena-efa",
  "Elastic Load Balancing (ALB/NLB)": "elb",
  "Elastic Network Adapter (ENA)": "ena-efa",
  "Fargate Spot": "fargate",
  "Gateway VPC Endpoints": "vpc-endpoints",
  "IAM Access Analyzer": "iam-access-analyzer",
  "Internet Gateway": "internet-gateway",
  "NAT Gateway": "nat-gateway",
  "Network ACLs": "network-acls",
  "Network Load Balancer": "elb",
  "RDS Proxy": "rds-proxy",
  "S3 Cross-Region Replication (CRR)": "s3-replication",
  "S3 Intelligent-Tiering": "s3",
  "S3 Lifecycle": "s3",
  "S3 Object Lock": "s3",
  "S3 Same-Region Replication (SRR)": "s3-replication",
  "S3 Versioning": "s3",
  "Security Groups": "security-groups",
  "Service Control Policies (SCPs)": "scp",
  "Tag policies": "tag-policies",
  "VPC Endpoints": "vpc-endpoints",
  "VPC Flow Logs": "vpc-flow-logs",
  "VPC Peering": "vpc-peering"
};
